name: Auto Assign Issues to Project

on:
  issues:
    types: [opened, closed, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'opened'
      with:
        project: "https://github.com/users/Danielhiversen/projects/1"
        column_name: 'To do'

    - name: Close issues
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: github.event.action == 'closed'
      with:
        project: "https://github.com/users/Danielhiversen/projects/1"
        column_name: 'Done'

    - name: Add comment
      uses: peter-evans/create-or-update-comment@v1.4.5
      if: github.event.label.name == 'missing-information'
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Please add missing information, @${{ github.event.issue.user.login }}
